### ISSUE TITLE
Don't hard code pacman cache directory

### ISSUE THREAD

**Issue by volklord** [lestofante/PacmanParallelizer#1]
https://github.com/lestofante/PacmanParallelizer/blob/master/pp.sh#L48 hard codes the the pacman cache directory, where it would be better to dynamically get it from the config file utilizing the pacman-conf command.    

`pacman-conf |awk '$1 ~ /^CacheDir/ {print $NF}'`    

I would define a variable like `pacmanCahceDir="$(pacman-conf | awk '$1 ~ /^CacheDir/ {print $NF}')"` and feed it to aria2c.

**Comment by Morganamilo** [comment]
Or just use pacman-conf as intended `pacmanCahceDir="$(pacman-conf CacheDir)"`

**Comment by volklord** [comment]
oh, even better, thanks, I didn't know that one :+1:

**Comment by lestofante** [comment]
thanks, fixed and released

**Comment by Morganamilo** [comment]
You missed the `$` so you're passing the string not the variable.

**Comment by lestofante** [comment]
ri-fixed
Do you have any suggestion how can i get pacman to think there is stuff to update for testing?
